remote_theme: pages-themes/minimal
# remote_theme: pages-themes/leap-day

title: Joseph Domguia
description: Everything is about learning and creation.

logo: /assets/img/photo-bw.jpeg
google_analytics: G-41KQNZMQDT
# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
