remote_theme: pages-themes/minimal
# remote_theme: pages-themes/leap-day

title: Joseph Domguia
description: Learn and Create

logo: /assets/img/djmlogo.png
# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]
